name: Compile LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Compile LaTeX Document
      run: pdflatex -interaction=nonstopmode -halt-on-error "Sahand Sorouri - Product Manager.tex"

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: "*.pdf"
