name: Compile LaTeX
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LaTeX
      run: sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
    - name: Compile LaTeX document
      run: pdflatex Sahand Sorouri - Product Manager.tex
    - name: Upload PDF to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: ./Sahand Sorouri - Product Manager.pdf
